import { LanguageType } from "../../types";

export const fr: LanguageType = {
  translation: {
    header: {
      title: "Kickdrum",
      subtitle: "Moteur de réservation Internet",
      myBookings: "MES RESERVATIONS",
      currency: "€EUR",
      login: "Connexion",
      logout: "Déconnexion",
      changeLanguage: "Changer de langue",
    },
    landingPageForm: {
      propertyName: "Nom de la propriété",
      checkIn: "Arrivée",
      checkOut: "Départ",
      guestType: "Type de client",
      rooms: "Chambres",
      selectDate: "Sélectionner une date",
      age: "Âge",
      search: "Rechercher",
      kids: "Enfants",
      adult: "Adulte",
      teens: "Adolescents",
      beds: "Lits",
      accessibility: "J'ai besoin d'une chambre accessible",
      military: "Je suis militaire",
      seniorCitizen: "J'ai des personnes âgées avec moi"
    },
    roomResultForm: {
      filterTitle: "Affiner vos résultats",
      roomResultTitle: "Résultats de la chambre",
      paginationFirst: "Affichage de",
      paginationSecond: "résultats"
    },
    stepper: {
      step1: "Choisissez une chambre",
      step2: "Choisissez un supplément",
      step3: "vérifier"
    },
    footer: {
      title: "Kickdrum",
      copyright: "© Kickdrum Groupe de Technologie S.A.S.",
      rights: "Tous droits réservés.",
    },
    error: {
      title: "Oops!",
      subtitle: "Désolé, une erreur inattendue s'est produite.",
    },
    generic: {
      amenitiesTitle: "Équipements",
      dealsAndPackagesTitle: "Offres et Forfaits",
      standardRatesTitle: "Tarifs Standards",
      inclusive: "Inclus",
      location: "Kickdrum",
      newPropertyTag: "Nou Propriété",
      perNight: "par nuit",
      promoCodeButton: "Appliquer",
      promoCodeInput: "Entrez un code promo",
      reviews: "Avis",
      selectPackageButton: "Sélectionner le Forfait",
      selectRoomButton: "Sélectionner la Chambre",
      specialDealTitle: "Offre Spéciale",
      editBillingInfo: "Modifier les informations de facturation",
      editTravellerInfo: "Modifier les informations du voyageur",
      nextBillingInfo: "Suivant : Informations de facturation",
      nextPaymentInfo: "Suivant : Informations de paiement",
      purchase: "Acheter",
      bookingsSubtitle: "Vos chambres sont disponibles ici!",
      booked: "Réservé"
    },
    itenary: {
      itenaryCheckout: "Check-out",
      itenaryContinueShopping: "Continuer les Achats",
      itenaryDueNow: "Dû Maintenant",
      itenaryDueResort: "Dû au Resort",
      itenaryEmail: "Entrer l'Email",
      itenarySpecialPromo: "Promo Spéciale",
      itenaryStayCompleted: "Séjour Terminé",
      itenaryTaxes: "Taxes, Suppléments, Frais",
      itenaryTitle: "Votre Itinéraire de Voyage",
      itenaryVAT: "TVA",
      itenaryRemove: "supprimer"
    },
    confirmation: {
      billingAddress: "Adresse de facturation",
      cancellationPolicy: "Copie expliquant la politique d'annulation, le cas échéant.",
      cancelRoom: "Annuler la chambre",
      city: "Ville",
      country: "Pays",
      email: "E-mail",
      firstName: "Prénom",
      lastName: "Nom de famille",
      guestInformation: "Information sur l'invité",
      nightlyRate: "Tarif par nuit",
      paymentId: "Identifiant de paiement",
      paymentInformation: "Informations de paiement",
      phone: "Téléphone",
      print: "Imprimer",
      roomTotalSummary: "Résumé total de la chambre",
      state: "État",
      subTotal: "Sous-total",
      total: "Total",
      upcomingReservation: "Réservation à venir",
      vat: "TVA",
      zipCode: "Code postal",
      cancelled: "Annulé",
      agreeToTerms: "J'accepte les conditions et politiques de voyage",
      specialOffers: "Envoyez-moi des offres spéciales",
      cardNumber: "Numéro de carte",
      mailingAddress1: "Adresse postale 1",
      mailingAddress2: "Adresse postale 2",
      needHelp: "Besoin d'aide",
      call: "Appeler",
      travellerInfo: "Informations du voyageur",
      billingInfo: "Informations de facturation",
      paymentInfo: "Informations de paiement"
    }
  },
};
