import { LanguageType } from "../../types";

export const hn: LanguageType = {
  translation: {
    header: {
      title: "Kickdrum",
      subtitle: "इंटरनेट बुकिंग इंजन",
      myBookings: "मेरी बुकिंग्स",
      currency: "₹INR",
      login: "लॉग इन करें",
      logout: "लॉग आउट करें",
      changeLanguage: "भाषा बदलें",
    },
    landingPageForm: {
      propertyName: "संपत्ति का नाम",
      checkIn: "चेक-इन",
      checkOut: "चेक-आउट",
      guestType: "ग्राहक प्रकार",
      rooms: "कमरे",
      selectDate: "तारीख चुनें",
      age: "उम्र",
      search: "खोज",
      kids: "बच्चे",
      adult: "वयस्क",
      teens: "किशोर",
      beds: "बिस्तर",
      accessibility: "मुझे एक पहुंचने योग्य कमरा चाहिए",
      military: "मैं सैन्य पर्सनल हूँ",
      seniorCitizen: "मेरे साथ वरिष्ठ नागरिक हैं"
    },
    roomResultForm: {
      filterTitle: "अपने परिणामों को संक्षेपित करें",
      roomResultTitle: "कक्ष परिणाम",
      paginationFirst: "दिखाना",
      paginationSecond: "परिणाम"
    },
    stepper: {
      step1: "कमरा चुनें",
      step2: "ऐड-ऑन चुनें",
      step3: "चेक-आउट"
    },
    footer: {
      title: "Kickdrum",
      copyright: "© किकड्रम टेक्नोलॉजी ग्रूप एलसीएलसी.",
      rights: "सभी अधिकार सुरक्षित।",
    },
    error: {
      title: "उफ़!",
      subtitle: "क्षमा करें, एक अप्रत्याशित त्रुटि उत्पन्न हुई है.",
    },
    generic: {
      amenitiesTitle: "सुविधाएं",
      dealsAndPackagesTitle: "डील्स और पैकेज",
      standardRatesTitle: "मानक दरें",
      inclusive: "सम्मिलित",
      location: "किकड्रम",
      newPropertyTag: "नई संपत्ति",
      perNight: "प्रति रात",
      promoCodeButton: "लागू करें",
      promoCodeInput: "प्रोमो कोड दर्ज करें",
      reviews: "समीक्षाएँ",
      selectPackageButton: "पैकेज चुनें",
      selectRoomButton: "कमरा चुनें",
      specialDealTitle: "विशेष सौदा",
      editBillingInfo: "बिलिंग जानकारी संपादित करें",
      editTravellerInfo: "यात्री जानकारी संपादित करें",
      nextBillingInfo: "अगला: बिलिंग जानकारी",
      nextPaymentInfo: "अगला: भुगतान जानकारी",
      purchase: "क्रय"

    },
    itenary: {
      itenaryCheckout: "चेक-आउट",
      itenaryContinueShopping: "खरीदारी जारी रखें",
      itenaryDueNow: "अब देना है",
      itenaryDueResort: "रिज़ॉर्ट पर देना है",
      itenaryEmail: "ईमेल दर्ज करें",
      itenarySpecialPromo: "विशेष प्रोमो",
      itenaryStayCompleted: "आपका रहना समाप्त हो गया है",
      itenaryTaxes: "कर, अतिरिक्त शुल्क, शुल्क",
      itenaryTitle: "आपकी यात्रा योजना",
      itenaryVAT: "वैट",
      itenaryRemove: "हटाएं"
    },
    confirmation: {
      billingAddress: "बिलिंग पता",
      cancellationPolicy: "अस्वीकृति नीति की व्याख्या कॉपी, यदि लागू हो",
      cancelRoom: "कमरा रद्द करें",
      city: "शहर",
      country: "देश",
      email: "ईमेल",
      firstName: "पहला नाम",
      lastName: "उपनाम",
      guestInformation: "अतिथि जानकारी",
      nightlyRate: "हर रात की दर",
      paymentId: "भुगतान आईडी",
      paymentInformation: "भुगतान की जानकारी",
      phone: "फ़ोन",
      print: "प्रिंट",
      roomTotalSummary: "कुल कमरे का संक्षिप्त",
      state: "राज्य",
      subTotal: "उप-योग",
      total: "कुल",
      upcomingReservation: "आगामी आरक्षण",
      vat: "वीएटी",
      zipCode: "पिन कोड",
      cancelled: "रद्द",
      agreeToTerms: "मैं यात्रा की नियम और नीतियों से सहमत हूँ",
      specialOffers: "मुझे विशेष प्रस्ताव भेजें",
      cardNumber: "कार्ड नंबर",
      mailingAddress1: "मेलिंग पता 1",
      mailingAddress2: "मेलिंग पता 2",
      needHelp: "मदद चाहिए",
      call: "कॉल करें",
      travellerInfo: "यात्री सूचना",
      billingInfo: "बिलिंग सूचना",
      paymentInfo: "भुगतान सूचना"
    }
  },
};
